#pragma once
// AUTOGENERATED by the project's CMakeLists.txt, do not edit manually
#include <string_view>
namespace pfp {
static constexpr std::string_view PROJECT_VERSION = "0.1.0-unknown";
static constexpr unsigned int PROJECT_VERSION_MAJOR = 0;
static constexpr unsigned int PROJECT_VERSION_MINOR = 1;
static constexpr unsigned int PROJECT_VERSION_PATCH = 0;
static constexpr std::string_view PROJECT_GIT_SHA1 "unknown";
} // namespace pfp
