name: CI

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Formatting
        run: find inc src tests -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \) | xargs clang-format -n --Werror

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Multi-Config Generator
        shell: bash
        run: |
          if cmake -B build -LA | grep -q CMAKE_CONFIGURATION_TYPES; then
            echo "CTEST_CONFIG_ARG=--config Release" >> $GITHUB_ENV
          else
            echo "CTEST_CONFIG_ARG=" >> $GITHUB_ENV
          fi

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=ON -DPFP_INSTALL_HOOKS=OFF

      - name: Build
        run: cmake --build build ${{ env.CTEST_CONFIG_ARG }}

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure
